import { 
  User, 
  Workspace, 
  PromptTemplate, 
  KnowledgeDoc, 
  AIProject, 
  SubscriptionPlan, 
  Invoice, 
  DailyUsage, 
  PostHogEventLog, 
  SystemOverview 
} from '../types';

export const INITIAL_USER: User = {
  id: 'usr_synapse_01',
  name: 'Alex Rivera',
  email: 'alex@novalabs.ai',
  role: 'admin',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  workspaceId: 'ws_synapse_alpha',
  plan: 'pro',
  tokensUsed: 642300,
  tokensLimit: 2000000,
  apiCallsCount: 4892,
  createdAt: '2026-01-15T08:00:00Z',
};

export const INITIAL_WORKSPACE: Workspace = {
  id: 'ws_synapse_alpha',
  name: 'Nova Labs Enterprise',
  slug: 'nova-labs',
  ownerId: 'usr_synapse_01',
  apiKey: 'syn_live_9f83a2e1d704bb49e6',
  apiCallsTotal: 18450,
  members: [
    {
      id: 'mem_1',
      userId: 'usr_synapse_01',
      name: 'Alex Rivera',
      email: 'alex@novalabs.ai',
      role: 'admin',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      joinedAt: '2026-01-15T08:00:00Z',
      status: 'active',
    },
    {
      id: 'mem_2',
      userId: 'usr_synapse_02',
      name: 'Elena Rostova',
      email: 'elena@novalabs.ai',
      role: 'member',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      joinedAt: '2026-02-01T10:30:00Z',
      status: 'active',
    },
    {
      id: 'mem_3',
      userId: 'usr_synapse_03',
      name: 'Marcus Vance',
      email: 'marcus@novalabs.ai',
      role: 'member',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      joinedAt: '2026-02-14T14:15:00Z',
      status: 'active',
    },
    {
      id: 'mem_4',
      userId: 'usr_synapse_04',
      name: 'Sophia Chen',
      email: 'sophia@novalabs.ai',
      role: 'viewer',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      joinedAt: '2026-03-01T09:00:00Z',
      status: 'active',
    },
  ],
  settings: {
    allowMemberInvites: true,
    requireTwoFactor: true,
    defaultModel: 'gemini-3.7-flash',
  },
};

export const INITIAL_PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    id: 'tmpl_1',
    title: 'Enterprise Code Review & Refactoring Engine',
    description: 'Deeply analyzes TypeScript, Python, or Go code for security vulnerabilities, race conditions, memory leaks, and O(n) algorithmic bottlenecks.',
    category: 'coding',
    template: 'You are a Senior Principal Staff Engineer. Perform a comprehensive code review on the following snippet:\n\nLanguage: {{language}}\nComponent: {{componentName}}\nContext / Requirements: {{context}}\n\n```{{language}}\n{{codeSnippet}}\n```\n\nProvide:\n1. Architecture & Security vulnerabilities (OWASP, memory leaks, thread safety)\n2. Performance bottlenecks & Big-O time/space complexity analysis\n3. Refactored production-ready implementation with idiomatic TypeScript/ESM conventions\n4. Recommended unit tests',
    variables: ['language', 'componentName', 'context', 'codeSnippet'],
    likes: 342,
    usesCount: 1890,
    isPublic: true,
    author: 'Nova Engineering Team',
  },
  {
    id: 'tmpl_2',
    title: 'High-Converting SaaS Landing Page Copywriter',
    description: 'Generates irresistible Value Propositions, Hero Headings, 3-tier Benefit frameworks, and objection-handling FAQs for B2B SaaS startups.',
    category: 'copywriting',
    template: 'Act as a world-class Conversion Copywriter. Generate conversion-optimized copy for our product:\n\nProduct Name: {{productName}}\nTarget Audience (ICP): {{targetAudience}}\nCore Problem Solved: {{coreProblem}}\nUnique Differentiator: {{differentiator}}\n\nOutput format:\n- 3 Compelling Hero Headlines (H1) + Subheadlines (H2)\n- Primary & Secondary CTA button micro-copy\n- 4 High-Impact Feature Benefit Bullets (Outcome focused)\n- 3 Customer Testimonial templates matching our ICP\n- 4 Objection-busting FAQ pairs',
    variables: ['productName', 'targetAudience', 'coreProblem', 'differentiator'],
    likes: 512,
    usesCount: 3410,
    isPublic: true,
    author: 'Growth Studio',
  },
  {
    id: 'tmpl_3',
    title: 'Executive Financial & Market Sentiment Analyzer',
    description: 'Extracts strategic insights, moat strength, unit economics risks, and catalysts from quarterly earnings or competitor pitch decks.',
    category: 'analysis',
    template: 'Analyze the following quarterly financial data or business proposal as a Venture Capital Managing Partner:\n\nCompany/Sector: {{companySector}}\nTimeframe: {{timeframe}}\nRaw Metrics / Summary: {{rawMetrics}}\n\nGenerate:\n1. Executive Summary & Growth Trajectory\n2. Gross Margin, CAC Payback, and Unit Economics evaluation\n3. Bull Case vs. Bear Case scenarios\n4. Top 3 Strategic recommendations for leadership',
    variables: ['companySector', 'timeframe', 'rawMetrics'],
    likes: 218,
    usesCount: 940,
    isPublic: true,
    author: 'FinTech Alpha',
  },
  {
    id: 'tmpl_4',
    title: 'Customer Support Escalation Resolver & RCA',
    description: 'Turns frustrated enterprise customer tickets into empathetic, solution-oriented resolution responses and Root Cause Analysis notes.',
    category: 'support',
    template: 'Draft an empathetic, high-tier Enterprise Customer Support response for the following ticket:\n\nCustomer Tier: {{customerTier}}\nIncident Summary: {{incidentSummary}}\nTechnical Root Cause: {{rootCause}}\nResolution/Fix ETA: {{eta}}\n\nEnsure tone is calm, accountable, highly transparent, and includes immediate mitigation steps plus post-mortem assurances.',
    variables: ['customerTier', 'incidentSummary', 'rootCause', 'eta'],
    likes: 185,
    usesCount: 1220,
    isPublic: true,
    author: 'CX Operations',
  },
  {
    id: 'tmpl_5',
    title: 'Product Requirements Document (PRD) Architect',
    description: 'Transforms high-level feature ideas into comprehensive engineering-ready PRDs with user stories, acceptance criteria, and edge cases.',
    category: 'product',
    template: 'Draft a complete Product Requirements Document (PRD) for the following initiative:\n\nFeature Name: {{featureName}}\nUser Persona: {{userPersona}}\nObjective / KPI to move: {{kpi}}\nScope & Constraints: {{constraints}}\n\nInclude:\n1. Problem Statement & User Journey\n2. Key Functional Requirements with Gherkin Acceptance Criteria (Given/When/Then)\n3. Non-functional requirements (Latency, Security, Mobile Responsiveness)\n4. Edge Cases & Out-of-Scope boundaries',
    variables: ['featureName', 'userPersona', 'kpi', 'constraints'],
    likes: 429,
    usesCount: 2750,
    isPublic: true,
    author: 'Product Strategy Group',
  },
];

export const INITIAL_KNOWLEDGE_DOCS: KnowledgeDoc[] = [
  {
    id: 'doc_1',
    name: 'Nova_Enterprise_Architecture_Security_Whitepaper.pdf',
    size: 2450000,
    type: 'pdf',
    summary: 'Comprehensive overview of Synapse Enterprise Cloud architecture, zero-trust token auth, AES-256 data encryption at rest, GDPR/SOC-2 Type II compliance standards, and multi-tenant isolation protocols.',
    keyInsights: [
      'Zero-trust microservices architecture with automated mTLS inter-service encryption',
      'End-to-end tokenized LLM request proxying with automatic PII redaction filters',
      '99.99% multi-region SLA with sub-50ms failover routing',
      'Compliant with SOC-2 Type II, ISO 27001, HIPAA, and EU GDPR standards',
    ],
    chunksCount: 24,
    embeddingsStatus: 'ready',
    uploadedAt: '2026-02-10T11:20:00Z',
    authorName: 'Alex Rivera',
    tokensEstimated: 8400,
  },
  {
    id: 'doc_2',
    name: 'Q3_Global_SaaS_AI_Benchmarks_2026.docx',
    size: 1180000,
    type: 'docx',
    summary: 'Industry market study analyzing AI SaaS adoption across Fortune 500 enterprises. Highlights 4.2x ROI on generative prompt automation, reduced customer ticket resolution times, and developer velocity metrics.',
    keyInsights: [
      'Average generative AI tool adoption increased by 142% year-over-year in SaaS engineering teams',
      'RAG knowledge retrieval reduces support resolution time from 32 minutes down to 4.5 minutes',
      'Hybrid model routing (Flash for high-frequency queries, Pro for deep STEM reasoning) reduces LLM API spend by 68%',
    ],
    chunksCount: 16,
    embeddingsStatus: 'ready',
    uploadedAt: '2026-02-22T16:45:00Z',
    authorName: 'Elena Rostova',
    tokensEstimated: 5200,
  },
  {
    id: 'doc_3',
    name: 'Customer_Support_SLA_Guidelines_v4.md',
    size: 450000,
    type: 'md',
    summary: 'Standard operating procedures for Enterprise client escalations, tier 1 to tier 3 routing mechanisms, refund policies, and emergency incident triage checklists.',
    keyInsights: [
      'Tier 1 responses must initiate within 15 minutes for critical P0 platform outages',
      'Automated root cause analysis post-mortems must be delivered to affected clients within 24 business hours',
      'Compensation credit calculation matrix for SLA dips below 99.9%',
    ],
    chunksCount: 8,
    embeddingsStatus: 'ready',
    uploadedAt: '2026-03-02T14:10:00Z',
    authorName: 'Marcus Vance',
    tokensEstimated: 2100,
  },
];

export const INITIAL_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'free',
    name: 'Starter Tier',
    tagline: 'Ideal for indie hackers, prototyping, and personal projects.',
    priceMonthly: 0,
    priceYearly: 0,
    tokensPerMonth: 100000,
    maxTeamMembers: 1,
    modelAccess: ['Gemini 3.7 Flash', 'Gemini 3.1 Flash Lite'],
    features: [
      '100,000 monthly AI tokens',
      'Streaming chat interface',
      'Up to 3 RAG document uploads',
      'Standard prompt templates',
      'Community discord support',
      'Basic token analytics',
    ],
  },
  {
    id: 'pro',
    name: 'Professional',
    tagline: 'High-growth startups and developers demanding speed & depth.',
    priceMonthly: 29,
    priceYearly: 290,
    tokensPerMonth: 2000000,
    maxTeamMembers: 5,
    popular: true,
    modelAccess: ['Gemini 3.7 Flash', 'Gemini 3.1 Flash Lite', 'Gemini 3.1 Pro Preview'],
    features: [
      '2,000,000 monthly AI tokens',
      'Priority streaming & ultra-low latency',
      'Unlimited RAG documents & embeddings',
      'Custom prompt studio with variables',
      'Team collaboration up to 5 members',
      'Stripe test billing & instant invoice PDFs',
      'PostHog analytics & telemetry dashboard',
      'Dedicated email support (24h SLA)',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise Scale',
    tagline: 'Full-scale organizations with custom SLA, SSO, and unlimited scale.',
    priceMonthly: 99,
    priceYearly: 990,
    tokensPerMonth: 10000000,
    maxTeamMembers: 50,
    modelAccess: ['Gemini 3.7 Flash', 'Gemini 3.1 Pro Preview', 'Gemini Live Voice & Video'],
    features: [
      '10,000,000+ monthly AI tokens',
      '99.99% Guaranteed uptime SLA',
      'Dedicated vector database clusters',
      'Custom LLM fine-tuning pipelines',
      'Role-based access & SAML/SSO auth',
      'Audit log exports & compliance vault',
      'Unlimited team members & shared workspaces',
      'Dedicated Solutions Architect support',
    ],
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv_2026_03_01',
    amount: 29.00,
    currency: 'USD',
    status: 'paid',
    date: '2026-03-01',
    planName: 'Professional Plan (Monthly)',
    pdfUrl: '#',
  },
  {
    id: 'inv_2026_02_01',
    amount: 29.00,
    currency: 'USD',
    status: 'paid',
    date: '2026-02-01',
    planName: 'Professional Plan (Monthly)',
    pdfUrl: '#',
  },
  {
    id: 'inv_2026_01_15',
    amount: 29.00,
    currency: 'USD',
    status: 'paid',
    date: '2026-01-15',
    planName: 'Professional Plan (Monthly)',
    pdfUrl: '#',
  },
];

export const INITIAL_DAILY_USAGE: DailyUsage[] = [
  { date: 'Aug 08', tokensUsed: 42100, apiCalls: 320, costEstimate: 0.12, latencyMs: 310, geminiFlashUsage: 35000, geminiProUsage: 7100 },
  { date: 'Aug 09', tokensUsed: 56400, apiCalls: 410, costEstimate: 0.16, latencyMs: 295, geminiFlashUsage: 48000, geminiProUsage: 8400 },
  { date: 'Aug 10', tokensUsed: 68900, apiCalls: 490, costEstimate: 0.21, latencyMs: 340, geminiFlashUsage: 54000, geminiProUsage: 14900 },
  { date: 'Aug 11', tokensUsed: 89200, apiCalls: 670, costEstimate: 0.28, latencyMs: 280, geminiFlashUsage: 71000, geminiProUsage: 18200 },
  { date: 'Aug 12', tokensUsed: 94300, apiCalls: 720, costEstimate: 0.31, latencyMs: 315, geminiFlashUsage: 75000, geminiProUsage: 19300 },
  { date: 'Aug 13', tokensUsed: 112000, apiCalls: 890, costEstimate: 0.39, latencyMs: 290, geminiFlashUsage: 89000, geminiProUsage: 23000 },
  { date: 'Aug 14', tokensUsed: 135400, apiCalls: 1040, costEstimate: 0.48, latencyMs: 275, geminiFlashUsage: 108000, geminiProUsage: 27400 },
  { date: 'Aug 15', tokensUsed: 144100, apiCalls: 1120, costEstimate: 0.52, latencyMs: 260, geminiFlashUsage: 115000, geminiProUsage: 29100 },
];

export const INITIAL_POSTHOG_LOGS: PostHogEventLog[] = [
  {
    id: 'evt_ph_01',
    event: 'ai_chat_completed',
    userId: 'usr_synapse_01',
    userEmail: 'alex@novalabs.ai',
    timestamp: '2026-08-15T06:20:12Z',
    properties: { model: 'gemini-3.7-flash', stream: true, tokens: 682, latencyMs: 310 },
  },
  {
    id: 'evt_ph_02',
    event: 'document_rag_query',
    userId: 'usr_synapse_02',
    userEmail: 'elena@novalabs.ai',
    timestamp: '2026-08-15T06:14:40Z',
    properties: { docId: 'doc_1', similarityScore: 0.94, chunksRetrieved: 3 },
  },
  {
    id: 'evt_ph_03',
    event: 'prompt_template_executed',
    userId: 'usr_synapse_01',
    userEmail: 'alex@novalabs.ai',
    timestamp: '2026-08-15T05:58:22Z',
    properties: { templateId: 'tmpl_1', category: 'coding' },
  },
  {
    id: 'evt_ph_04',
    event: 'stripe_billing_session_verified',
    userId: 'usr_synapse_01',
    userEmail: 'alex@novalabs.ai',
    timestamp: '2026-08-15T04:30:10Z',
    properties: { plan: 'pro', amount: 29, currency: 'usd' },
  },
];

export const INITIAL_PROJECTS: AIProject[] = [
  {
    id: 'proj_1',
    name: 'Automated Lead Qualification & Enrichment Pipeline',
    description: 'Extracts company information, matches tech stacks with Gemini, and drafts personalized B2B outreach sequences directly into Slack and CRM.',
    status: 'active',
    category: 'Sales Automation',
    steps: [
      { id: 'st_1', title: 'Parse Inbound Prospect Data', type: 'extract', config: { schema: 'contact, domain, budget' }, status: 'completed' },
      { id: 'st_2', title: 'Enrich Tech Stack with Gemini Reasoning', type: 'prompt', config: { model: 'gemini-3.7-flash' }, status: 'completed' },
      { id: 'st_3', title: 'Generate Custom Outreach Email Draft', type: 'prompt', config: { tone: 'executive' }, status: 'completed' },
      { id: 'st_4', title: 'Webhook Post to CRM Endpoint', type: 'webhook', config: { url: 'https://api.crm.novalabs.ai/v1/leads' }, status: 'idle' },
    ],
    lastRun: '2026-08-15T05:40:00Z',
    collaborators: ['Alex Rivera', 'Elena Rostova'],
    createdAt: '2026-02-18T10:00:00Z',
  },
  {
    id: 'proj_2',
    name: 'Customer Support Escalation & Ticket Triage Bot',
    description: 'Auto-classifies incoming Zendesk/Intercom support tickets, searches internal RAG documentation, and drafts verified resolution responses.',
    status: 'active',
    category: 'Customer Experience',
    steps: [
      { id: 'st_21', title: 'Ticket Ingestion & Sentiment Classification', type: 'extract', config: { categories: ['billing', 'bug', 'feature', 'sla'] }, status: 'completed' },
      { id: 'st_22', title: 'RAG Knowledge Base Context Fetch', type: 'summarize', config: { topK: 3 }, status: 'completed' },
      { id: 'st_23', title: 'Draft Verified Solution with Confidence Score', type: 'prompt', config: { model: 'gemini-3.7-flash' }, status: 'completed' },
    ],
    lastRun: '2026-08-15T06:12:00Z',
    collaborators: ['Marcus Vance', 'Alex Rivera'],
    createdAt: '2026-03-01T08:30:00Z',
  },
];

export const INITIAL_SYSTEM_OVERVIEW: SystemOverview = {
  totalUsers: 14820,
  activeWorkspaces: 3240,
  mrr: 94180,
  totalTokensProcessed: 894500000,
  systemUptime: 99.98,
  averageLatencyMs: 275,
  errorRate: 0.04,
};
