import React, { useState } from 'react';
import { KnowledgeDoc, User } from '../types';
import { INITIAL_KNOWLEDGE_DOCS } from '../lib/mockData';
import { 
  FileText, 
  UploadCloud, 
  Sparkles, 
  Search, 
  Send, 
  BookOpen, 
  Layers, 
  CheckCircle2, 
  Clock, 
  ShieldCheck, 
  ArrowUpRight, 
  FileCode,
  Trash2,
  HelpCircle,
  Eye,
  Hash
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { api } from '../lib/api';
import { useToast } from './Toast';
import ReactMarkdown from 'react-markdown';

interface DocumentRAGProps {
  user: User;
  onUpdateUserTokens: (tokens: number) => void;
  actionTrigger?: { id: string; timestamp: number } | null;
}

export const DocumentRAG: React.FC<DocumentRAGProps> = ({ user, onUpdateUserTokens, actionTrigger }) => {
  const { showToast } = useToast();
  const [documents, setDocuments] = useState<KnowledgeDoc[]>(INITIAL_KNOWLEDGE_DOCS);
  const [selectedDoc, setSelectedDoc] = useState<KnowledgeDoc>(INITIAL_KNOWLEDGE_DOCS[0]);
  const [searchQuery, setSearchQuery] = useState('');
  
  // Upload modal state
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [newDocName, setNewDocName] = useState('');
  const [newDocContent, setNewDocContent] = useState('');
  const [newDocType, setNewDocType] = useState('pdf');
  const [isAnalyzingDoc, setIsAnalyzingDoc] = useState(false);

  // Handle external action trigger (e.g. from Command Palette)
  React.useEffect(() => {
    if (actionTrigger?.id === 'upload_doc') {
      setShowUploadModal(true);
    }
  }, [actionTrigger?.timestamp]);

  // RAG Query state
  const [ragQuestion, setRagQuestion] = useState('');
  const [isQueryingRAG, setIsQueryingRAG] = useState(false);
  const [ragAnswer, setRagAnswer] = useState<string | null>(null);
  const [ragCitations, setRagCitations] = useState<any[]>([]);

  // Active view tab in document preview (Summary vs Chunks)
  const [activeDocTab, setActiveDocTab] = useState<'summary' | 'chunks'>('summary');

  // Filter documents
  const filteredDocs = documents.filter((d) =>
    d.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    d.summary.toLowerCase().includes(searchQuery.toLowerCase())
  );

  // Handle uploading and analyzing a new document with Gemini
  const handleUploadDocument = async () => {
    if (!newDocName.trim() || !newDocContent.trim() || isAnalyzingDoc) return;
    setIsAnalyzingDoc(true);

    try {
      const analysis = await api.analyzeDocument(newDocName, newDocContent, newDocType);

      const newDoc: KnowledgeDoc = {
        id: `doc_${Date.now()}`,
        name: newDocName,
        size: newDocContent.length,
        type: newDocType,
        summary: analysis.summary || 'Executive summary generated by Gemini AI.',
        keyInsights: analysis.keyInsights || [
          'Key insight extracted from uploaded document',
          'Automated semantic chunks indexed into knowledge vault',
        ],
        chunksCount: analysis.chunks?.length || 8,
        chunks: analysis.chunks || [
          { id: 'c1', chunkIndex: 0, text: newDocContent.slice(0, 300), similarityScore: 0.98 },
        ],
        embeddingsStatus: 'ready',
        uploadedAt: new Date().toISOString(),
        authorName: user.name,
        tokensEstimated: analysis.tokensEstimated || Math.ceil(newDocContent.length / 4),
      };

      setDocuments([newDoc, ...documents]);
      setSelectedDoc(newDoc);
      setShowUploadModal(false);
      setNewDocName('');
      setNewDocContent('');
      showToast('success', 'Document Processed & Indexed', `Extracted summary and generated semantic embeddings.`);
      api.logTelemetry('document_uploaded', { docName: newDoc.name, size: newDoc.size });
    } catch (err: any) {
      showToast('error', 'Analysis Failed', err.message);
    } finally {
      setIsAnalyzingDoc(false);
    }
  };

  // Run Grounded RAG Query against active document
  const handleRunRAGQuery = async (prefillQuery?: string) => {
    const queryToUse = prefillQuery || ragQuestion;
    if (!queryToUse.trim() || isQueryingRAG) return;

    setIsQueryingRAG(true);
    setRagAnswer(null);
    setRagCitations([]);

    try {
      const result = await api.ragQuery(queryToUse, selectedDoc.summary + '\n' + selectedDoc.keyInsights.join('\n'), selectedDoc.name);
      setRagAnswer(result.answer);
      setRagCitations(result.citations || []);
      onUpdateUserTokens(180);
      showToast('success', 'RAG Query Grounded', `Answer synthesized with high-relevance citations.`);
      api.logTelemetry('document_rag_query', { docId: selectedDoc.id, query: queryToUse });
    } catch (err: any) {
      showToast('error', 'RAG Query Failed', err.message);
    } finally {
      setIsQueryingRAG(false);
    }
  };

  return (
    <div className="flex h-[calc(100vh-4rem)] bg-[#050505] text-[#FAFAFA] overflow-hidden">
      
      {/* Left Knowledge Base Directory */}
      <aside className="w-80 bg-[#080808] border-r border-white/10 flex flex-col shrink-0">
        <div className="p-4 border-b border-white/10 space-y-3">
          <div className="flex items-center justify-between">
            <h2 className="text-xs font-black uppercase tracking-[0.2em] text-white flex items-center">
              <BookOpen className="w-4 h-4 text-indigo-400 mr-2" />
              Document Vault
            </h2>
            <button
              id="upload-doc-modal-btn"
              onClick={() => setShowUploadModal(true)}
              className="px-2.5 py-1.5 rounded-lg bg-indigo-500 hover:bg-indigo-400 text-white font-bold text-[10px] uppercase tracking-wider flex items-center space-x-1 transition-all shadow-sm"
            >
              <UploadCloud className="w-3.5 h-3.5" />
              <span>Upload Doc</span>
            </button>
          </div>

          <div className="relative">
            <Search className="w-3.5 h-3.5 absolute left-3 top-3 text-white/40" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search knowledge docs..."
              className="w-full pl-9 pr-3 py-2 rounded-xl bg-[#050505] border border-white/10 text-xs text-white placeholder-white/20 focus:outline-none focus:border-indigo-500"
            />
          </div>
        </div>

        {/* Documents List */}
        <div className="flex-1 overflow-y-auto p-3 space-y-2">
          {filteredDocs.map((doc) => {
            const isSelected = doc.id === selectedDoc.id;
            return (
              <div
                key={doc.id}
                onClick={() => {
                  setSelectedDoc(doc);
                  setRagAnswer(null);
                }}
                className={`p-3.5 rounded-xl border text-xs cursor-pointer transition-all ${
                  isSelected
                    ? 'bg-white/10 border-indigo-500 text-white shadow-md'
                    : 'bg-[#050505] border-white/10 text-white/50 hover:bg-white/5 hover:text-white'
                }`}
              >
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-[9px] uppercase font-black tracking-widest px-1.5 py-0.5 rounded bg-white/5 text-indigo-400 border border-white/5">
                    {doc.type}
                  </span>
                  <span className="text-[10px] text-emerald-400 font-mono flex items-center font-bold">
                    <CheckCircle2 className="w-3 h-3 mr-1" />
                    Indexed
                  </span>
                </div>
                <h4 className="font-bold text-white leading-snug line-clamp-1">{doc.name}</h4>
                <p className="text-[11px] text-white/40 mt-1 line-clamp-2 leading-relaxed font-normal">
                  {doc.summary}
                </p>
                <div className="mt-2.5 flex items-center justify-between text-[10px] font-bold uppercase tracking-wider text-white/30 pt-2 border-t border-white/5">
                  <span>{(doc.size / 1024).toFixed(0)} KB</span>
                  <span>{doc.chunksCount} chunks</span>
                </div>
              </div>
            );
          })}
        </div>
      </aside>

      {/* Main Document & RAG Canvas */}
      <main className="flex-1 flex flex-col bg-[#050505] overflow-y-auto p-4 sm:p-6 space-y-6">
        
        {/* Document Header & Tab Navigation */}
        <div className="p-6 rounded-2xl bg-[#080808] border border-white/10 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-start space-x-3.5">
            <div className="p-3 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 shrink-0">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <h1 className="text-xl sm:text-2xl font-black uppercase tracking-tight text-white leading-tight">{selectedDoc.name}</h1>
              <div className="flex flex-wrap items-center gap-3 text-xs text-white/40 mt-1.5">
                <span className="flex items-center">
                  <Clock className="w-3.5 h-3.5 mr-1 text-white/30" />
                  {new Date(selectedDoc.uploadedAt).toLocaleDateString()}
                </span>
                <span>•</span>
                <span>Author: {selectedDoc.authorName}</span>
                <span>•</span>
                <span className="text-indigo-400 font-mono font-bold">~{selectedDoc.tokensEstimated} tokens</span>
              </div>
            </div>
          </div>

          <div className="flex items-center space-x-1.5 p-1 rounded-xl bg-[#050505] border border-white/10">
            <button
              onClick={() => setActiveDocTab('summary')}
              className={`px-3.5 py-2 rounded-lg text-xs font-bold uppercase tracking-wider transition-all ${
                activeDocTab === 'summary'
                  ? 'bg-white/10 text-white shadow-sm'
                  : 'text-white/40 hover:text-white'
              }`}
            >
              Summary & Insights
            </button>
            <button
              onClick={() => setActiveDocTab('chunks')}
              className={`px-3.5 py-2 rounded-lg text-xs font-bold uppercase tracking-wider transition-all ${
                activeDocTab === 'chunks'
                  ? 'bg-white/10 text-white shadow-sm'
                  : 'text-white/40 hover:text-white'
              }`}
            >
              Chunk Inspector ({selectedDoc.chunksCount})
            </button>
          </div>
        </div>

        {/* Tab 1: Executive Summary & Key Insights */}
        {activeDocTab === 'summary' && (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            
            {/* 2 Cols: Summary */}
            <div className="lg:col-span-2 p-6 rounded-2xl bg-[#080808] border border-white/10 space-y-4">
              <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/50 flex items-center">
                <Sparkles className="w-4 h-4 text-indigo-400 mr-1.5" />
                AI Executive Summary
              </h3>
              <p className="text-xs sm:text-sm text-white/80 leading-relaxed whitespace-pre-wrap">
                {selectedDoc.summary}
              </p>

              <div className="pt-4 border-t border-white/10">
                <h4 className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/40 mb-3">
                  Strategic Takeaways
                </h4>
                <div className="space-y-2">
                  {selectedDoc.keyInsights.map((insight, idx) => (
                    <div key={idx} className="flex items-start text-xs text-white/80 bg-[#050505] p-3.5 rounded-xl border border-white/5">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400 mr-2.5 shrink-0 mt-0.5" />
                      <span>{insight}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* 1 Col: Vector Knowledge Meta */}
            <div className="p-6 rounded-2xl bg-[#080808] border border-white/10 space-y-4">
              <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/50 flex items-center">
                <Layers className="w-4 h-4 text-indigo-400 mr-1.5" />
                Vector Index Status
              </h3>
              <div className="space-y-3 text-xs">
                <div className="flex justify-between py-2 border-b border-white/10">
                  <span className="text-white/40">Embedding Model</span>
                  <span className="text-white font-mono">text-embedding-004</span>
                </div>
                <div className="flex justify-between py-2 border-b border-white/10">
                  <span className="text-white/40">Dimensions</span>
                  <span className="text-white font-mono">1536-d</span>
                </div>
                <div className="flex justify-between py-2 border-b border-white/10">
                  <span className="text-white/40">Similarity Metric</span>
                  <span className="text-white font-mono">Cosine Similarity</span>
                </div>
                <div className="flex justify-between py-2 border-b border-white/10">
                  <span className="text-white/40">Security Vault</span>
                  <span className="text-emerald-400 font-mono flex items-center font-bold">
                    <ShieldCheck className="w-3.5 h-3.5 mr-1" />
                    SOC-2 Type II
                  </span>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Tab 2: Chunk Inspector */}
        {activeDocTab === 'chunks' && (
          <div className="p-6 rounded-2xl bg-[#080808] border border-white/10 space-y-4">
            <div className="flex items-center justify-between pb-2 border-b border-white/10">
              <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/50 flex items-center">
                <Hash className="w-4 h-4 text-indigo-400 mr-1.5" />
                Vector Chunks & Similarity Scores
              </h3>
              <span className="text-[10px] text-white/40 uppercase font-bold tracking-wider">Overlapping partitions</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {(selectedDoc.chunks || [
                { id: 'c1', chunkIndex: 0, text: selectedDoc.summary.slice(0, 220), similarityScore: 0.96 },
                { id: 'c2', chunkIndex: 1, text: selectedDoc.keyInsights[0] || 'Technical architecture overview chunk...', similarityScore: 0.93 },
                { id: 'c3', chunkIndex: 2, text: selectedDoc.keyInsights[1] || 'SLA and security compliance requirements...', similarityScore: 0.89 },
              ]).map((chunk, idx) => (
                <div key={idx} className="p-4 rounded-xl bg-[#050505] border border-white/10 space-y-2">
                  <div className="flex items-center justify-between text-[11px]">
                    <span className="font-mono text-white/50 font-bold">Chunk #{chunk.chunkIndex ?? idx}</span>
                    <span className="text-emerald-400 font-mono font-bold">
                      Score: {(chunk.similarityScore ?? 0.95).toFixed(2)}
                    </span>
                  </div>
                  <p className="text-xs text-white/70 leading-relaxed font-mono">
                    "{chunk.text}"
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Grounded RAG Interactive Q&A Search */}
        <div className="p-6 rounded-2xl bg-[#080808] border border-white/10 space-y-4">
          <div className="flex items-center justify-between pb-2 border-b border-white/10">
            <div>
              <h3 className="text-base font-black uppercase tracking-tight text-white flex items-center">
                <Search className="w-4 h-4 text-indigo-400 mr-2" />
                Grounded RAG Search & Q&A
              </h3>
              <p className="text-xs text-white/40">Query this document with Gemini 3.7 Flash using grounded citations</p>
            </div>
            <span className="text-xs text-white/40 font-mono hidden sm:inline">Context: {selectedDoc.name}</span>
          </div>

          {/* Quick Starter Chips */}
          <div className="flex flex-wrap gap-2 text-xs">
            {[
              `What are the core security compliance standards?`,
              `What is the ROI on generative AI adoption?`,
              `What are the SLA response times for P0 incidents?`,
            ].map((preset) => (
              <button
                key={preset}
                onClick={() => {
                  setRagQuestion(preset);
                  handleRunRAGQuery(preset);
                }}
                className="px-3.5 py-2 rounded-xl bg-[#050505] hover:bg-white/10 border border-white/10 text-white/70 hover:text-white text-xs transition-colors"
              >
                "{preset}"
              </button>
            ))}
          </div>

          {/* Input Box */}
          <div className="flex items-center gap-2">
            <input
              type="text"
              value={ragQuestion}
              onChange={(e) => setRagQuestion(e.target.value)}
              placeholder={`Ask any specific question about ${selectedDoc.name}...`}
              onKeyDown={(e) => e.key === 'Enter' && handleRunRAGQuery()}
              className="flex-1 px-4 py-3 rounded-xl bg-[#050505] border border-white/10 text-xs sm:text-sm text-white placeholder-white/20 focus:outline-none focus:border-indigo-500"
            />
            <button
              id="rag-query-btn"
              onClick={() => handleRunRAGQuery()}
              disabled={!ragQuestion.trim() || isQueryingRAG}
              className="px-5 py-3 rounded-xl bg-indigo-500 hover:bg-indigo-400 disabled:opacity-40 text-white font-bold text-xs uppercase tracking-wider flex items-center space-x-1.5 transition-all shadow-md shrink-0"
            >
              {isQueryingRAG ? <Sparkles className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
              <span>{isQueryingRAG ? 'Synthesizing...' : 'Query RAG'}</span>
            </button>
          </div>

          {/* RAG Answer Display */}
          {ragAnswer && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="p-5 rounded-xl bg-[#050505] border border-indigo-500/40 space-y-3 mt-4"
            >
              <div className="flex items-center justify-between text-xs text-indigo-400 font-bold uppercase tracking-wider pb-2 border-b border-white/10">
                <span className="flex items-center">
                  <CheckCircle2 className="w-4 h-4 mr-1.5" />
                  Grounded Synthesis Result
                </span>
                <span className="text-white/40 font-mono">100% Document Verified</span>
              </div>
              <div className="text-xs sm:text-sm text-white/90 leading-relaxed markdown-body">
                <ReactMarkdown>{ragAnswer}</ReactMarkdown>
              </div>

              {ragCitations.length > 0 && (
                <div className="pt-3 border-t border-white/5 flex flex-wrap gap-2 text-[11px] text-white/40">
                  <span className="font-bold text-white/50 uppercase tracking-wider">Citations:</span>
                  {ragCitations.map((c, i) => (
                    <span key={i} className="px-2 py-0.5 rounded bg-white/5 border border-white/10 text-indigo-300 font-mono">
                      📄 {c.title}
                    </span>
                  ))}
                </div>
              )}
            </motion.div>
          )}
        </div>
      </main>

      {/* Upload Document Modal */}
      <AnimatePresence>
        {showUploadModal && (
          <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="w-full max-w-2xl bg-[#080808] border border-white/10 rounded-2xl shadow-2xl p-6 space-y-4"
            >
              <div className="flex items-center justify-between pb-3 border-b border-white/10">
                <div className="flex items-center space-x-2">
                  <div className="p-2 rounded-xl bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                    <UploadCloud className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="text-base font-black uppercase tracking-tight text-white">Upload & Analyze Document</h3>
                    <p className="text-xs text-white/40">Gemini extracts executive summaries, takeaways & vector chunks</p>
                  </div>
                </div>
                <button
                  onClick={() => setShowUploadModal(false)}
                  className="text-white/40 hover:text-white text-xs font-bold"
                >
                  ✕
                </button>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-[10px] font-bold uppercase tracking-wider text-white/40 mb-1">Document Title</label>
                  <input
                    type="text"
                    value={newDocName}
                    onChange={(e) => setNewDocName(e.target.value)}
                    placeholder="e.g. Q4_Engineering_Roadmap_2026.pdf"
                    className="w-full px-3 py-2 rounded-xl bg-[#050505] border border-white/10 text-xs text-white placeholder-white/20 focus:outline-none focus:border-indigo-500"
                  />
                </div>
                <div>
                  <label className="block text-[10px] font-bold uppercase tracking-wider text-white/40 mb-1">Document Type</label>
                  <select
                    value={newDocType}
                    onChange={(e) => setNewDocType(e.target.value)}
                    className="w-full px-3 py-2 rounded-xl bg-[#050505] border border-white/10 text-xs text-white focus:outline-none focus:border-indigo-500"
                  >
                    <option value="pdf" className="bg-[#080808]">PDF Document (.pdf)</option>
                    <option value="docx" className="bg-[#080808]">Word Document (.docx)</option>
                    <option value="md" className="bg-[#080808]">Markdown (.md)</option>
                    <option value="txt" className="bg-[#080808]">Plain Text (.txt)</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-[10px] font-bold uppercase tracking-wider text-white/40 mb-1">
                  Document Content (Paste text, extract, or transcript)
                </label>
                <textarea
                  rows={6}
                  value={newDocContent}
                  onChange={(e) => setNewDocContent(e.target.value)}
                  placeholder="Paste raw text, transcript, product specs, or policy rules here..."
                  className="w-full px-3 py-2.5 rounded-xl bg-[#050505] border border-white/10 text-xs text-white placeholder-white/20 focus:outline-none focus:border-indigo-500 font-mono"
                />
              </div>

              <div className="flex justify-end space-x-2 pt-2">
                <button
                  onClick={() => setShowUploadModal(false)}
                  className="px-4 py-2 rounded-xl bg-white/5 hover:bg-white/10 text-white/70 text-xs font-bold uppercase tracking-wider"
                >
                  Cancel
                </button>
                <button
                  id="submit-doc-upload-btn"
                  onClick={handleUploadDocument}
                  disabled={!newDocName.trim() || !newDocContent.trim() || isAnalyzingDoc}
                  className="px-5 py-2 rounded-xl bg-indigo-500 hover:bg-indigo-400 disabled:opacity-40 text-white font-bold text-xs uppercase tracking-wider flex items-center space-x-1.5"
                >
                  {isAnalyzingDoc ? <Sparkles className="w-3.5 h-3.5 animate-spin" /> : <UploadCloud className="w-3.5 h-3.5" />}
                  <span>{isAnalyzingDoc ? 'Vectorizing...' : 'Index Document'}</span>
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};
